FROM python:3.12.5-bullseye

RUN pip install numpy==1.26.3
RUN pip install pyarrow==15.0.0
RUN pip install pandas==2.2.0
RUN pip install requests==2.31.0
RUN pip install matplotlib==3.8.2
RUN pip install coverage==7.2.3
RUN pip install parameterized==0.9.0