FROM python:3.12.5-bullseye

RUN pip install --upgrade pip \
    && pip install numpy==1.26.3 \
    && pip install pyarrow==15.0.0 \     
    && pip install pandas==2.2.0 \ 
    && pip install requests==2.31.0 \ 
    && pip install matplotlib==3.8.2 \ 
    && pip install coverage==7.2.3 \ 
    && pip install parameterized==0.9.0